name: number_editing_controller
description: Number Editing Controller - number or amount editing controller
version: 1.0.2
homepage: https://github.com/nerdy-pro/flutter_number_editing_controller

environment:
  sdk: ">=2.19.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dependency_validator: ^3.0.0
  dart_code_metrics: ^5.7.2

flutter:
